Test failed prod deploy (#10)
* do exit

* fix error setter?

* dont exit again

* actually do exit

diff --git a/.github/workflows/manual-deploy-prod.yaml b/.github/workflows/manual-deploy-prod.yaml
--- a/.github/workflows/manual-deploy-prod.yaml
+++ b/.github/workflows/manual-deploy-prod.yaml
@@ -10,7 +10,8 @@ jobs:
       - name: Main Branch Check
         if: ${{ !startsWith(github.ref, 'refs/heads/main') }}
         run: |
-          echo "::error Deployment to prod must be from main branch"
+          echo "::error ::Deployment to prod must be from main branch"
+          exit 1
 
       - uses: actions/checkout@v2
       - uses: actions/setup-node@v2
